openapi: 3.0.3
info:
  title: Neu Scholar Agent API
  version: 1.0.0
  description: API cho AgentX gồm metadata, xử lý câu hỏi và lấy dữ liệu

servers:
  - url: https://neu-scholar.onrender.com

paths:
  /metadata:
    get:
      summary: Lấy thông tin cấu hình & khả năng của Agent
      responses:
        '200':
          description: Thông tin Agent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataResponse'

  /ask:
    post:
      summary: Gửi câu hỏi để Agent xử lý
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AskRequest'
      responses:
        '200':
          description: Kết quả trả lời từ Agent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AskResponse'
        '400':
          description: Lỗi request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /data:
    get:
      summary: Lấy dữ liệu hiện có của Agent
      responses:
        '200':
          description: Danh sách dữ liệu
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataResponse'

components:
  schemas:
    MetadataResponse:
      type: object
      properties:
        name:
          type: string
        version:
          type: string
        capabilities:
          type: array
          items:
            type: string
        model:
          type: object
          properties:
            name:
              type: string
            provider:
              type: string

    AskRequest:
      type: object
      required:
        - query
        - sessionId
      properties:
        query:
          type: string
        sessionId:
          type: string
        params:
          type: object
          properties:
            stream:
              type: boolean

    AskResponse:
      type: object
      properties:
        answer:
          type: string
        sessionId:
          type: string

    DataResponse:
      type: object
      properties:
        items:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string

    Error:
      type: object
      properties:
        message:
          type: string
